#!/bin/bash

set -e

PRG=$1

# `bear` is required by clang-tidy
# `declaration-after-statement` enforces variable declarations upfront (encourages being tidy and focused!)
echo "==> Compiling: $PRG"

# -Werror
bear -- gcc -o /tmp/tmp -Wall -Wextra -Wdeclaration-after-statement -Wpedantic -g "$PRG"

echo "==> Running clang-tidy..."
clang-tidy "$PRG"

echo "==> Running cppcheck..."
cppcheck $PRG

echo "OK"
